#!/usr/bin/env bash
# ============================================================================
# Dovecot Library
# Functions for configuring Dovecot IMAP/POP3 server
# ============================================================================

# Dependencies: None (uses global variables from main script)

# ============================================================================
# DOVECOT CONFIGURATION
# ============================================================================

configure_dovecot() {
    print_section "Configuring Dovecot"
    
    log_step "Backing up original configuration..."
    [[ -f "$DOVECOT_DIR/dovecot.conf" ]] && cp "$DOVECOT_DIR/dovecot.conf" "$DOVECOT_DIR/dovecot.conf.backup.$(date +%Y%m%d)"
    
    log_step "Creating virtual mail user..."
    if ! id -u vmail >/dev/null 2>&1; then
        useradd -r -u $VMAIL_UID -g mail -d "$VMAIL_DIR" -s /usr/sbin/nologin -c "Virtual Mail User" vmail
    fi
    
    mkdir -p "$VMAIL_DIR"
    chown -R vmail:mail "$VMAIL_DIR"
    chmod -R 770 "$VMAIL_DIR"
    
    log_step "Generating dovecot.conf..."
    
    cat > "$DOVECOT_DIR/dovecot.conf" << 'DOVECOTCONF'
# ============================================================================
# DOVECOT MAIN CONFIGURATION
# Generated by interactive mail server installation script
# ============================================================================

# ----------------------------------------------------------------------------
# PROTOCOLS
# Which protocols to enable (IMAP, POP3, LMTP)
# ----------------------------------------------------------------------------

# Enable IMAP (recommended), POP3, and LMTP protocols
# IMAP: Modern email access protocol (supports folders, flags, etc.)
# POP3: Legacy protocol (downloads and deletes from server)
# LMTP: Local Mail Transfer Protocol (receives mail from Postfix)
protocols = imap pop3 lmtp

# ----------------------------------------------------------------------------
# NETWORK SETTINGS
# Control which addresses and ports Dovecot listens on
# ----------------------------------------------------------------------------

# Listen on all IPv4 and IPv6 addresses
listen = *, ::

# ----------------------------------------------------------------------------
# LOGGING
# Configure how Dovecot logs information
# ----------------------------------------------------------------------------

# Timestamp format for log entries
log_timestamp = "%Y-%m-%d %H:%M:%S "

# Where to send log messages (uses syslog mail facility)
syslog_facility = mail

# Log authentication successes and failures
auth_verbose = yes
auth_debug = no
auth_debug_passwords = no

# Log mail process information
mail_debug = no
verbose_ssl = no

# ----------------------------------------------------------------------------
# SSL/TLS CONFIGURATION
# Configure encryption for IMAP/POP3 connections
# ----------------------------------------------------------------------------

# SSL is required for all connections
# Options: yes (allow plain), no (disable), required (force SSL)
ssl = required

# Path to SSL certificate (will be set up by Certbot)
ssl_cert = </etc/letsencrypt/live/HOSTNAME_PLACEHOLDER/fullchain.pem

# Path to SSL private key
ssl_key = </etc/letsencrypt/live/HOSTNAME_PLACEHOLDER/privkey.pem

# Disable old, insecure SSL/TLS versions
# Only allow TLS 1.2 and 1.3
ssl_min_protocol = TLSv1.2
ssl_protocols = !SSLv2 !SSLv3 !TLSv1 !TLSv1.1

# Use strong cipher suites only - Mozilla Modern profile
# Excludes all weak/deprecated ciphers (3DES, CBC mode, RC4, etc.)
ssl_cipher_list = ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

# Prefer server cipher order (more secure)
ssl_prefer_server_ciphers = yes

# Diffie-Hellman parameters for forward secrecy
# Generate with: openssl dhparam -out /etc/dovecot/dh.pem 4096
#ssl_dh = </etc/dovecot/dh.pem

# ----------------------------------------------------------------------------
# MAIL LOCATION
# Where and how mailboxes are stored
# ----------------------------------------------------------------------------

# Mailbox format and location
# maildir: One file per message (more reliable than mbox)
# /var/vmail/%d/%n: domain/username structure
#   %d = domain part of email (example.com)
#   %n = username part of email (john)
mail_location = maildir:/var/vmail/%d/%n/Maildir

# User and group for mail files
mail_uid = 5000
mail_gid = 5000

# Privileged group for mail access
mail_privileged_group = mail

# First and last valid UID for mail users
first_valid_uid = 5000
last_valid_uid = 5000

# First and last valid GID for mail users  
first_valid_gid = 5000
last_valid_gid = 5000

# ----------------------------------------------------------------------------
# MAILBOX CONFIGURATION
# Configure default mailbox names and special folders
# ----------------------------------------------------------------------------

# Define the namespace for user mailboxes
namespace inbox {
  # This is the inbox namespace
  inbox = yes
  
  # Folder separator character (/ or .)
  separator = /
  
  # Prefix for mailbox names (empty = no prefix)
  prefix = 
  
  # Define special-use folders (as per RFC 6154)
  # These are recognized by mail clients
  
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  
  mailbox Spam {
    auto = subscribe
    special_use = \Junk
  }
  
  mailbox Archive {
    auto = subscribe
    special_use = \Archive
  }
}

# ----------------------------------------------------------------------------
# AUTHENTICATION
# Configure how users authenticate
# ----------------------------------------------------------------------------

# Disable plaintext authentication unless using SSL/TLS
disable_plaintext_auth = yes

# Authentication mechanisms to offer
# PLAIN: Username and password (encrypted by TLS)
# LOGIN: Legacy method for old clients
auth_mechanisms = plain login

# Include SQL authentication configuration
!include auth-sql.conf.ext

# ----------------------------------------------------------------------------
# USER DATABASE
# Where to look up user information
# ----------------------------------------------------------------------------

# Use SQL for user database
userdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

# ----------------------------------------------------------------------------
# PASSWORD DATABASE  
# Where to verify passwords
# ----------------------------------------------------------------------------

# Use SQL for password verification
passdb {
  driver = sql
  args = /etc/dovecot/dovecot-sql.conf.ext
}

# ----------------------------------------------------------------------------
# SERVICE CONFIGURATION
# Configure Dovecot's various services
# ----------------------------------------------------------------------------

# IMAP Service
service imap-login {
  # Standard IMAP port (unencrypted, STARTTLS available)
  inet_listener imap {
    port = 143
  }
  
  # IMAPS port (TLS wrapped from the start)
  inet_listener imaps {
    port = 993
    ssl = yes
  }
  
  # Number of processes to pre-fork
  process_min_avail = 1
  
  # Maximum number of IMAP processes
  process_limit = 1024
}

# POP3 Service
service pop3-login {
  # Standard POP3 port
  inet_listener pop3 {
    port = 110
  }
  
  # POP3S port (TLS wrapped)
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
  
  process_min_avail = 1
  process_limit = 1024
}

# LMTP Service (receives mail from Postfix)
service lmtp {
  # Unix socket for Postfix to connect to
  unix_listener /var/spool/postfix/private/dovecot-lmtp {
    mode = 0666
    user = postfix
    group = postfix
  }
  
  # Number of LMTP processes
  process_min_avail = 0
  process_limit = 1024
}

# Authentication Service (for Postfix SASL)
service auth {
  # Unix socket for Postfix SMTP auth
  unix_listener /var/spool/postfix/private/auth {
    mode = 0666
    user = postfix
    group = postfix
  }
  
  # Unix socket for user database lookups
  unix_listener auth-userdb {
    mode = 0666
    user = vmail
    group = mail
  }
  
  # Auth process settings
  process_min_avail = 1
  process_limit = 1024
}

# Authentication worker processes
service auth-worker {
  # Number of auth worker processes
  # Should be at least the number of passdb/userdb connections
  user = root
  process_limit = 100
}

# Dictionary service (for quota and other data)
service dict {
  unix_listener dict {
    mode = 0666
    user = vmail
    group = mail
  }
}

# ----------------------------------------------------------------------------
# PROTOCOL-SPECIFIC SETTINGS
# ----------------------------------------------------------------------------

# IMAP-specific settings
protocol imap {
  # Maximum number of connections per IP address
  mail_max_userip_connections = 20
  
  # IMAP capabilities
  # IDLE: Server can notify client of new mail
  imap_idle_notify_interval = 2 mins
  
  # Maximum number of IMAP commands pipelined
  imap_max_line_length = 64k
}

# POP3-specific settings
protocol pop3 {
  # Maximum connections per IP
  mail_max_userip_connections = 10
  
  # Format for POP3 UIDL identifiers
  pop3_uidl_format = %08Xu%08Xv
  
  # Keep messages marked with \Seen flag
  pop3_save_uidl = yes
  
  # Don't leave messages on server
  pop3_delete_type = flag
}

# LMTP-specific settings
protocol lmtp {
  # Deliver to Spam folder if message is marked as spam
  # This works with Sieve filters
  postmaster_address = postmaster@PRIMARY_DOMAIN_PLACEHOLDER
  
  # Plugins to load for LMTP
  mail_plugins = $mail_plugins sieve
}

# ----------------------------------------------------------------------------
# PLUGIN CONFIGURATION
# ----------------------------------------------------------------------------

plugin {
  # Sieve mail filtering
  # Users can create filters to organize mail automatically
  sieve = ~/.dovecot.sieve
  sieve_dir = ~/sieve
  
  # Global sieve scripts (before user scripts)
  # Uncomment to enable global spam filtering
  #sieve_before = /var/vmail/sieve/spam-global.sieve
  
  # Default sieve script for all users
  #sieve_default = /var/vmail/sieve/default.sieve
  
  # Quota settings (if enabled)
  # Limit each user to 5GB by default
  quota = maildir:User quota
  quota_rule = *:storage=5GB
  
  # Don't count Trash against quota
  quota_rule2 = Trash:storage=+10%%
  
  # Don't count Spam against quota  
  quota_rule3 = Spam:storage=+10%%
  
  # Quota warning at 90%
  quota_warning = storage=90%% quota-warning 90 %u
  quota_warning2 = storage=95%% quota-warning 95 %u
}

# Load plugins
mail_plugins = quota

# ----------------------------------------------------------------------------
# PERFORMANCE TUNING
# ----------------------------------------------------------------------------

# Cache mail headers and bodies for better performance
mail_cache_fields = flags
mail_always_cache_fields = imap.envelope

# Reduce disk I/O for better performance
mail_fsync = optimized

# Allow Dovecot to use sendfile() for better performance
mail_nfs_storage = no
mail_nfs_index = no

# Connection caching
imap_idle_notify_interval = 2 mins

# Process titles for debugging
process_title = yes

# ============================================================================
# END OF MAIN CONFIGURATION
# ============================================================================
DOVECOTCONF

    # Replace placeholders
    sed -i "s/HOSTNAME_PLACEHOLDER/$MAIL_HOSTNAME/g" "$DOVECOT_DIR/dovecot.conf"
    sed -i "s/PRIMARY_DOMAIN_PLACEHOLDER/$PRIMARY_DOMAIN/g" "$DOVECOT_DIR/dovecot.conf"
    
    # Create SQL configuration
    create_dovecot_sql_config
    
    # Create auth-sql.conf.ext if it doesn't exist
    touch "$DOVECOT_DIR/auth-sql.conf.ext"
    
    log_success "Dovecot configuration complete with extensive comments"
}

create_dovecot_sql_config() {
    log_step "Creating Dovecot SQL configuration..."
    
    cat > "$DOVECOT_DIR/dovecot-sql.conf.ext" << EOF
# ============================================================================
# DOVECOT SQL CONFIGURATION
# This file configures how Dovecot connects to the MySQL database
# to authenticate users and look up mailbox information
# ============================================================================

# ----------------------------------------------------------------------------
# DATABASE DRIVER
# ----------------------------------------------------------------------------

# Use MySQL driver
# Other options: pgsql (PostgreSQL), sqlite
driver = mysql

# ----------------------------------------------------------------------------
# DATABASE CONNECTION
# ----------------------------------------------------------------------------

# Connection string format:
# host=<hostname> port=<port> dbname=<database> user=<username> password=<password>
#
# IMPORTANT: Keep this file secure! It contains database credentials.
# Permissions should be: chmod 600 /etc/dovecot/dovecot-sql.conf.ext
connect = host=localhost port=3306 dbname=mail user=mailuser password=$DB_PASSWORD

# ----------------------------------------------------------------------------
# DEFAULT PASSWORD SCHEME
# ----------------------------------------------------------------------------

# How passwords are encrypted in the database
# Options:
#   SHA512-CRYPT: Strong, recommended (what we use)
#   SHA256-CRYPT: Strong, alternative
#   MD5-CRYPT: Weak, legacy
#   PLAIN: No encryption (NOT RECOMMENDED)
#   CRYPT: System crypt()
default_pass_scheme = SHA512-CRYPT

# ----------------------------------------------------------------------------
# PASSWORD QUERY
# ----------------------------------------------------------------------------

# SQL query to verify user passwords
# %u = full username (user@domain.com)
# %n = username part (user)
# %d = domain part (domain.com)
#
# This query must return:
#   - user: The username (used for logging)
#   - password: The encrypted password hash
#
# The query checks if the user exists and is enabled
password_query = SELECT email as user, password FROM mail_users WHERE email = '%u' AND enabled = 1

# ----------------------------------------------------------------------------
# USER QUERY
# ----------------------------------------------------------------------------

# SQL query to get user mailbox information
# This query must return:
#   - uid: Unix user ID (we use 5000 for vmail)
#   - gid: Unix group ID (we use 5000 for vmail)
#   - home: Home directory for the mailbox
#
# The mailbox path is: /var/vmail/domain.com/username/
user_query = SELECT 5000 as uid, 5000 as gid, '/var/vmail/%d/%n' as home, 'maildir:/var/vmail/%d/%n/Maildir' as mail FROM mail_users WHERE email = '%u' AND enabled = 1

# ----------------------------------------------------------------------------
# ITERATE QUERY (Optional)
# ----------------------------------------------------------------------------

# Query used by doveadm to list all users
# Useful for administrative tasks
iterate_query = SELECT email as user FROM mail_users WHERE enabled = 1

# ============================================================================
# SECURITY NOTES
# ============================================================================
#
# 1. This file contains sensitive database credentials
#    Set permissions: chmod 600 /etc/dovecot/dovecot-sql.conf.ext
#
# 2. The database user (mailuser) only needs SELECT permissions
#    It should NOT have INSERT, UPDATE, or DELETE permissions
#
# 3. Passwords in the database should ALWAYS be hashed
#    Never store plaintext passwords!
#
# 4. To generate a password hash for testing:
#    doveadm pw -s SHA512-CRYPT -p yourpassword
#
# ============================================================================
EOF

    chmod 600 "$DOVECOT_DIR/dovecot-sql.conf.ext"
    chown root:root "$DOVECOT_DIR/dovecot-sql.conf.ext"
    
    log_success "Dovecot SQL configuration created (mode 600)"
}
