#!/usr/bin/env bash
# ============================================================================
# Postfix Library
# Functions for configuring Postfix MTA (Mail Transfer Agent)
# ============================================================================

# Dependencies: None (uses global variables from main script)

# ============================================================================
# POSTFIX CONFIGURATION
# ============================================================================

configure_postfix() {
    print_section "Configuring Postfix"
    
    log_step "Backing up original configuration..."
    [[ -f "$POSTFIX_DIR/main.cf" ]] && cp "$POSTFIX_DIR/main.cf" "$POSTFIX_DIR/main.cf.backup.$(date +%Y%m%d)"
    [[ -f "$POSTFIX_DIR/master.cf" ]] && cp "$POSTFIX_DIR/master.cf" "$POSTFIX_DIR/master.cf.backup.$(date +%Y%m%d)"
    
    log_step "Generating main.cf..."
    
    cat > "$POSTFIX_DIR/main.cf" << 'MAINCONF'
# ============================================================================
# POSTFIX MAIN CONFIGURATION
# Generated by interactive mail server installation script
# ============================================================================

# ----------------------------------------------------------------------------
# BASIC SETTINGS
# These define the server's identity and basic behavior
# ----------------------------------------------------------------------------

# The fully qualified domain name of this mail server
# This is what other mail servers see when connecting to you
myhostname = HOSTNAME_PLACEHOLDER

# The domain that appears in the "From" address for locally-posted mail
# Usually set to your primary domain
myorigin = PRIMARY_DOMAIN_PLACEHOLDER

# The domain name that this server considers "local"
# Typically this is just the server hostname and localhost
mydomain = PRIMARY_DOMAIN_PLACEHOLDER

# List of domains that are delivered locally (not forwarded)
# For virtual domains, we leave this minimal
mydestination = $myhostname, localhost.$mydomain, localhost

# Networks that are allowed to relay mail through this server
# Be very careful with this - only trusted networks should be here
mynetworks = 127.0.0.0/8, [::1]/128

# Which network interfaces to listen on
# "all" means listen on all available network interfaces
inet_interfaces = all

# IP protocol versions to use (ipv4, ipv6, or both)
inet_protocols = all

# ----------------------------------------------------------------------------
# VIRTUAL DOMAIN CONFIGURATION
# These settings enable support for multiple mail domains
# ----------------------------------------------------------------------------

# Tell Postfix which domains are virtual (stored in database)
# This MySQL query checks if a domain exists in mail_domains table
virtual_mailbox_domains = mysql:/etc/postfix/mysql-virtual-domains.cf

# Map email addresses to mailbox locations
# Returns the mailbox path for each email address
virtual_mailbox_maps = mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf

# Map email aliases to their destination addresses
# Allows info@example.com to forward to admin@example.com
virtual_alias_maps = mysql:/etc/postfix/mysql-virtual-alias-maps.cf

# The transport method for virtual domains
# "dovecot" means deliver to Dovecot's LMTP service
virtual_transport = lmtp:unix:private/dovecot-lmtp

# Base directory where all virtual mailboxes are stored
virtual_mailbox_base = /var/vmail

# UID (user ID) for all virtual mailbox files
# Using a dedicated user (5000) for security
virtual_uid_maps = static:5000

# GID (group ID) for all virtual mailbox files
virtual_gid_maps = static:5000

# ----------------------------------------------------------------------------
# MESSAGE SIZE LIMITS
# Control how large messages can be
# ----------------------------------------------------------------------------

# Maximum size of any single email message (25MB here)
# Adjust based on your needs (value in bytes)
message_size_limit = 26214400

# Maximum size of a user's entire mailbox (0 = unlimited)
# Quota is better enforced at the Dovecot level
mailbox_size_limit = 0

# ----------------------------------------------------------------------------
# TLS/SSL CONFIGURATION (OUTGOING MAIL)
# These settings control encryption when SENDING mail
# ----------------------------------------------------------------------------

# Enable TLS for outgoing mail connections
smtp_use_tls = yes

# Use TLS if available, but don't require it
# Options: none, may, encrypt, dane, dane-only, fingerprint, verify, secure
smtp_tls_security_level = may

# Certificate Authority bundle for verifying remote certificates
smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt

# Cache TLS session data to improve performance
smtp_tls_session_cache_database = btree:${data_directory}/smtp_scache

# Disable old, insecure SSL/TLS versions
# Only allow TLSv1.2 and TLSv1.3
smtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1

# Use high-security cipher suites only
smtp_tls_ciphers = high

# Minimum Diffie-Hellman key size
smtp_tls_dh_min_bits = 2048

# Log TLS connection details for debugging
smtp_tls_loglevel = 1

# ----------------------------------------------------------------------------
# TLS/SSL CONFIGURATION (INCOMING MAIL)
# These settings control encryption when RECEIVING mail
# ----------------------------------------------------------------------------

# Enable TLS for incoming mail connections
smtpd_use_tls = yes

# Accept both encrypted and unencrypted connections
# The submission port (587) will require encryption
smtpd_tls_security_level = may

# Path to your SSL certificate file
# This will be populated by Certbot
smtpd_tls_cert_file = /etc/letsencrypt/live/HOSTNAME_PLACEHOLDER/fullchain.pem

# Path to your SSL private key file
smtpd_tls_key_file = /etc/letsencrypt/live/HOSTNAME_PLACEHOLDER/privkey.pem

# Cache TLS session data
smtpd_tls_session_cache_database = btree:${data_directory}/smtpd_scache

# Disable old, insecure SSL/TLS versions
smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1

# Use high-security cipher suites (Mozilla Modern compatibility)
# Only allow TLS 1.2+ with strong ciphers - no weak/deprecated ciphers
smtpd_tls_ciphers = high
smtpd_tls_mandatory_ciphers = high
smtpd_tls_exclude_ciphers = 
    aNULL, eNULL, EXPORT, DES, 3DES, MD5, PSK, RC4, 
    DSS, SEED, IDEA, CAMELLIA, CBC

# Prefer server cipher order (more secure)
smtpd_tls_prefer_server_ciphers = yes

# Minimum Diffie-Hellman key size (2048 minimum, 4096 recommended)
smtpd_tls_dh_min_bits = 2048

# Log TLS connection details
smtpd_tls_loglevel = 1

# ----------------------------------------------------------------------------
# SASL AUTHENTICATION
# Allows users to send mail after proving their identity
# ----------------------------------------------------------------------------

# Use Dovecot for SASL authentication
smtpd_sasl_type = dovecot

# Path to Dovecot's authentication socket
smtpd_sasl_path = private/auth

# Enable SASL authentication
smtpd_sasl_auth_enable = yes

# Don't allow anonymous authentication
smtpd_sasl_security_options = noanonymous

# Support for broken email clients (Outlook, etc)
broken_sasl_auth_clients = yes

# The domain to append to unqualified usernames
smtpd_sasl_local_domain = $myhostname

# ----------------------------------------------------------------------------
# RELAY RESTRICTIONS
# Control who can send mail through this server
# ----------------------------------------------------------------------------

# Main relay policy
# These rules determine who can send mail through your server
smtpd_relay_restrictions = 
    permit_mynetworks,            # Allow mail from trusted networks
    permit_sasl_authenticated,    # Allow authenticated users
    defer_unauth_destination      # Temporarily reject others

# ----------------------------------------------------------------------------
# RECIPIENT RESTRICTIONS
# Control which recipients will accept mail for
# ----------------------------------------------------------------------------

smtpd_recipient_restrictions =
    permit_mynetworks,                    # Allow from trusted networks
    permit_sasl_authenticated,            # Allow authenticated users
    reject_unauth_destination,            # Reject if not our domain
    reject_invalid_hostname,              # Reject malformed hostnames
    reject_non_fqdn_hostname,             # Reject non-FQDN hostnames
    reject_non_fqdn_sender,               # Reject non-FQDN senders
    reject_non_fqdn_recipient,            # Reject non-FQDN recipients
    reject_unknown_sender_domain,         # Reject unknown sender domains
    reject_unknown_recipient_domain,      # Reject unknown recipient domains
    reject_rbl_client zen.spamhaus.org,   # Check Spamhaus blocklist
    reject_rbl_client bl.spamcop.net,     # Check SpamCop blocklist
    permit                                # Accept if passed all checks

# ----------------------------------------------------------------------------
# SENDER RESTRICTIONS
# Validate the sender's address
# ----------------------------------------------------------------------------

smtpd_sender_restrictions =
    permit_mynetworks,              # Allow from trusted networks
    permit_sasl_authenticated,      # Allow authenticated users
    reject_non_fqdn_sender,         # Reject non-FQDN sender addresses
    reject_unknown_sender_domain    # Reject unknown sender domains

# ----------------------------------------------------------------------------
# HELO/EHLO RESTRICTIONS
# Validate the HELO/EHLO hostname provided by connecting servers
# ----------------------------------------------------------------------------

smtpd_helo_restrictions =
    permit_mynetworks,                # Allow from trusted networks
    permit_sasl_authenticated,        # Allow authenticated users
    reject_invalid_helo_hostname,     # Reject malformed HELO names
    reject_non_fqdn_helo_hostname,    # Reject non-FQDN HELO names
    reject_unknown_helo_hostname      # Reject unknown HELO names

# Require HELO/EHLO at the start of SMTP sessions
smtpd_helo_required = yes

# ----------------------------------------------------------------------------
# LOGGING
# Control what information is logged
# ----------------------------------------------------------------------------

# Where to write mail logs
# On systemd systems, this goes to journald
maillog_file = /var/log/mail.log

# Log level for debugging (0=off, 1=normal, 2=verbose)
# Set to 2 temporarily if you need to troubleshoot issues
debug_peer_level = 2

# ----------------------------------------------------------------------------
# PERFORMANCE TUNING
# Adjust these based on your server's capacity
# ----------------------------------------------------------------------------

# Maximum number of parallel deliveries to the same destination
default_destination_concurrency_limit = 20

# Maximum number of parallel local deliveries
local_destination_concurrency_limit = 2

# Maximum number of Postfix processes
default_process_limit = 100

# ----------------------------------------------------------------------------
# MAIL QUEUE SETTINGS
# Control how mail is queued and retried
# ----------------------------------------------------------------------------

# How long to keep trying to deliver a message (5 days)
maximal_queue_lifetime = 5d

# How long to keep bounce messages (5 days)
bounce_queue_lifetime = 5d

# Minimum time between delivery attempts (5 minutes)
minimal_backoff_time = 300s

# Maximum time between delivery attempts (1 hour)
maximal_backoff_time = 3600s

# ----------------------------------------------------------------------------
# MISC SECURITY SETTINGS
# ----------------------------------------------------------------------------

# Disable VRFY command (prevents email address harvesting)
disable_vrfy_command = yes

# Strict RFC compliance for mail address syntax
strict_rfc821_envelopes = yes

# Don't send notifications when delivery is delayed
# (many spammers use fake sender addresses)
notify_classes = resource, software

# Reject messages with unknown local recipients quickly
unknown_local_recipient_reject_code = 550

# ----------------------------------------------------------------------------
# SMTPD BANNER
# What remote servers see when they connect
# ----------------------------------------------------------------------------

# Custom banner (don't reveal version info for security)
smtpd_banner = $myhostname ESMTP

# ----------------------------------------------------------------------------
# POLICYD-SPF CONFIGURATION
# Enables SPF (Sender Policy Framework) checking
# ----------------------------------------------------------------------------

# Check SPF records for incoming mail
# This helps prevent email spoofing
POLICYD_SPF_PLACEHOLDER

# ----------------------------------------------------------------------------
# MILTER CONFIGURATION (DKIM)
# Mail filters for DKIM signing
# ----------------------------------------------------------------------------

DKIM_PLACEHOLDER

# ============================================================================
# END OF MAIN CONFIGURATION
# ============================================================================
MAINCONF

    # Replace placeholders
    sed -i "s/HOSTNAME_PLACEHOLDER/$HOSTNAME/g" "$POSTFIX_DIR/main.cf"
    sed -i "s/PRIMARY_DOMAIN_PLACEHOLDER/$PRIMARY_DOMAIN/g" "$POSTFIX_DIR/main.cf"
    
    # Add Policyd-SPF if enabled
    if $ENABLE_POLICYD_SPF; then
        sed -i "s/POLICYD_SPF_PLACEHOLDER/policyd-spf_time_limit = 3600/" "$POSTFIX_DIR/main.cf"
    else
        sed -i "s/POLICYD_SPF_PLACEHOLDER//g" "$POSTFIX_DIR/main.cf"
    fi
    
    # Add DKIM configuration if enabled
    if $ENABLE_DKIM; then
        cat >> "$POSTFIX_DIR/main.cf" << 'EOF'

# DKIM signing with OpenDKIM
milter_default_action = accept
milter_protocol = 6
smtpd_milters = inet:localhost:8891
non_smtpd_milters = $smtpd_milters
EOF
        sed -i "s/DKIM_PLACEHOLDER//g" "$POSTFIX_DIR/main.cf"
    else
        sed -i "s/DKIM_PLACEHOLDER//g" "$POSTFIX_DIR/main.cf"
    fi
    
    log_success "Generated main.cf with extensive comments"
    
    # Create MySQL configuration files
    create_mysql_configs
    
    # Configure master.cf
    configure_postfix_master
    
    log_success "Postfix configuration complete"
}

create_mysql_configs() {
    log_step "Creating MySQL query configuration files..."
    
    # Virtual domains query
    cat > "$POSTFIX_DIR/mysql-virtual-domains.cf" << EOF
# ============================================================================
# MYSQL CONFIGURATION: Virtual Domains
# This file tells Postfix how to query for valid virtual domains
# ============================================================================

# Database connection settings
user = mailuser
password = $DB_PASSWORD
hosts = localhost
dbname = mail

# SQL query to check if a domain is valid
# %s is replaced with the domain being queried
# Returns 1 if the domain exists and is enabled, nothing otherwise
query = SELECT 1 FROM mail_domains WHERE domain = '%s' AND enabled = 1
EOF
    chmod 640 "$POSTFIX_DIR/mysql-virtual-domains.cf"
    
    # Virtual mailbox maps query
    cat > "$POSTFIX_DIR/mysql-virtual-mailbox-maps.cf" << EOF
# ============================================================================
# MYSQL CONFIGURATION: Virtual Mailbox Maps
# This file tells Postfix where to deliver mail for each user
# ============================================================================

# Database connection settings
user = mailuser
password = $DB_PASSWORD
hosts = localhost
dbname = mail

# SQL query to get the mailbox path for an email address
# %s is replaced with the full email address (user@domain.com)
# Returns the path where mail should be stored
# Format: domain/username (e.g., example.com/john)
query = SELECT CONCAT(SUBSTRING_INDEX(email, '@', -1), '/', SUBSTRING_INDEX(email, '@', 1), '/') FROM mail_users WHERE email = '%s' AND enabled = 1
EOF
    chmod 640 "$POSTFIX_DIR/mysql-virtual-mailbox-maps.cf"
    
    # Virtual alias maps query
    cat > "$POSTFIX_DIR/mysql-virtual-alias-maps.cf" << EOF
# ============================================================================
# MYSQL CONFIGURATION: Virtual Alias Maps
# This file tells Postfix how to handle email aliases (forwards)
# ============================================================================

# Database connection settings
user = mailuser
password = $DB_PASSWORD
hosts = localhost
dbname = mail

# SQL query to resolve email aliases
# %s is replaced with the source email address
# Returns the destination email address(es)
# Multiple destinations can be returned (one per row) for list-like behavior
query = SELECT destination_email FROM mail_aliases WHERE source_email = '%s' AND enabled = 1
EOF
    chmod 640 "$POSTFIX_DIR/mysql-virtual-alias-maps.cf"
    
    log_success "MySQL configuration files created"
}

configure_postfix_master() {
    log_step "Configuring master.cf (service definitions)..."
    
    cat > "$POSTFIX_DIR/master.cf" << 'MASTERCONF'
# ============================================================================
# POSTFIX MASTER CONFIGURATION
# This file defines all Postfix services and how they run
# Generated by interactive mail server installation script
# ============================================================================

# ----------------------------------------------------------------------------
# SMTP SERVICE (Port 25)
# Traditional SMTP - accepts mail from other mail servers
# ----------------------------------------------------------------------------
smtp      inet  n       -       y       -       -       smtpd
  # n = no privileged operation
  # - = no limit on number of processes
  # y = run in chroot jail (more secure)
  # - = no wakeup timer
  # - = no process limit
  # smtpd = the service to run

# ----------------------------------------------------------------------------
# SUBMISSION SERVICE (Port 587)
# Used by mail clients to submit outgoing mail
# Requires authentication and encryption (TLS)
# ----------------------------------------------------------------------------
submission inet n       -       y       -       -       smtpd
  # Override settings to require security
  -o syslog_name=postfix/submission        # Separate log identifier
  -o smtpd_tls_security_level=encrypt      # REQUIRE encryption (mandatory)
  -o smtpd_sasl_auth_enable=yes            # REQUIRE authentication
  -o smtpd_sasl_type=dovecot               # Use Dovecot for auth
  -o smtpd_sasl_path=private/auth          # Path to auth socket
  -o smtpd_sasl_security_options=noanonymous
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject_all
  -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject_all
  -o milter_macro_daemon_name=ORIGINATING  # Mark as originating mail

# ----------------------------------------------------------------------------
# SMTPS SERVICE (Port 465)
# Legacy encrypted SMTP (SMTP over SSL)
# Similar to submission but wraps connection in TLS from the start
# ----------------------------------------------------------------------------
smtps     inet  n       -       y       -       -       smtpd
  -o syslog_name=postfix/smtps
  -o smtpd_tls_wrappermode=yes             # TLS wrapper mode (immediate TLS)
  -o smtpd_tls_security_level=encrypt      # REQUIRE encryption
  -o smtpd_sasl_auth_enable=yes            # REQUIRE authentication
  -o smtpd_sasl_type=dovecot
  -o smtpd_sasl_path=private/auth
  -o smtpd_client_restrictions=permit_sasl_authenticated,reject
  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject_all
  -o smtpd_recipient_restrictions=permit_sasl_authenticated,reject_all
  -o milter_macro_daemon_name=ORIGINATING

# ----------------------------------------------------------------------------
# INTERNAL SERVICES
# These services handle mail processing internally
# ----------------------------------------------------------------------------

# Pickup: picks up mail from the maildrop queue
pickup    unix  n       -       y       60      1       pickup

# Cleanup: processes message headers and body
cleanup   unix  n       -       y       -       0       cleanup

# Queue manager: manages the mail queue
qmgr      unix  n       -       n       300     1       qmgr

# TLS manager: manages TLS session cache
tlsmgr    unix  -       -       y       1000?   1       tlsmgr

# Rewriter: rewrites addresses
rewrite   unix  -       -       y       -       -       trivial-rewrite

# Bounce: generates bounce messages
bounce    unix  -       -       y       -       0       bounce

# Defer: generates deferral messages
defer     unix  -       -       y       -       0       bounce

# Trace: generates delivery reports
trace     unix  -       -       y       -       0       bounce

# Verify: address verification
verify    unix  -       -       y       -       1       verify

# Flush: flushes the mail queue
flush     unix  n       -       y       1000?   0       flush

# Proxymap: provides access to Postfix lookup tables
proxymap  unix  -       -       n       -       -       proxymap

# Proxywrite: write access to maps
proxywrite unix -       -       n       -       1       proxymap

# ----------------------------------------------------------------------------
# TRANSPORT SERVICES
# These services deliver mail
# ----------------------------------------------------------------------------

# SMTP: delivers mail to remote hosts
smtp      unix  -       -       y       -       -       smtp

# Relay: relays mail through a relay host
relay     unix  -       -       y       -       -       smtp
  -o smtp_fallback_relay=

# ----------------------------------------------------------------------------
# MISCELLANEOUS SERVICES
# ----------------------------------------------------------------------------

# Show queue: displays queue contents
showq     unix  n       -       y       -       -       showq

# Error: generates error messages
error     unix  -       -       y       -       -       error

# Retry: retries failed deliveries
retry     unix  -       -       y       -       -       error

# Discard: discards messages
discard   unix  -       -       y       -       -       discard

# Local: delivers to local mailboxes (not used with virtual domains)
local     unix  -       n       n       -       -       local

# Virtual: delivers to virtual mailboxes (not used with Dovecot LMTP)
virtual   unix  -       n       n       -       -       virtual

# LMTP: Local Mail Transfer Protocol client
lmtp      unix  -       -       y       -       -       lmtp

# Anvil: connection rate limiting
anvil     unix  -       -       y       -       1       anvil

# Scache: connection cache
scache    unix  -       -       y       -       1       scache

# ----------------------------------------------------------------------------
# POLICYD-SPF SERVICE
# Checks SPF records for incoming mail
# ----------------------------------------------------------------------------
POLICYD_SPF_PLACEHOLDER

# ============================================================================
# END OF MASTER CONFIGURATION
# ============================================================================
MASTERCONF

    # Add Policyd-SPF if enabled
    if $ENABLE_POLICYD_SPF; then
        cat >> "$POSTFIX_DIR/master.cf" << 'EOF'
# SPF policy checking
# This service checks if the sending server is authorized by SPF
policyd-spf  unix  -       n       n       -       0       spawn
  user=policyd-spf argv=/usr/bin/policyd-spf
EOF
        sed -i "s/POLICYD_SPF_PLACEHOLDER//g" "$POSTFIX_DIR/master.cf"
    else
        sed -i "s/POLICYD_SPF_PLACEHOLDER//g" "$POSTFIX_DIR/master.cf"
    fi
    
    log_success "master.cf configured with extensive comments"
}
